name: Quality Check

on:
    push:
        branches: [main]

jobs:
    quality-checks:
        name: Quality Checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
            - name: Run Quality Checks
              uses: ./.github/actions/quality-checks
